"""create admin role

Revision ID: 0002
Revises: 0001
Create Date: 2025-08-14 17:49:43.879051

"""

from collections.abc import Sequence
from sqlalchemy.dialects.postgresql import insert

from alembic import op
import sqlalchemy as sa
from app.authorization.entities import RoleEntity
from app.authorization.typedef import ADMIN_ROLE_NAME

# revision identifiers, used by Alembic.
type RevisionType = str | Sequence[str] | None
revision: str = "0002"
down_revision: RevisionType = "0001"
branch_labels: RevisionType = None
depends_on: RevisionType = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        insert(RoleEntity)
        .values(
            codename=ADMIN_ROLE_NAME,
            description="Administrator role with full access",
        )
        .on_conflict_do_nothing()
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.delete(RoleEntity).where(RoleEntity.codename == ADMIN_ROLE_NAME)
    )
    # ### end Alembic commands ###
