"""create group and relations with roles and users

Revision ID: 0003
Revises: 0002
Create Date: 2025-08-14 18:03:16.102318

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
type RevisionType = str | Sequence[str] | None
revision: str = "0003"
down_revision: RevisionType = "0002"
branch_labels: RevisionType = None
depends_on: RevisionType = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _ = op.create_table(
        "authorization__groups",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    _ = op.create_table(
        "authorization__roles_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("authorization__roles_id", sa.Uuid(), nullable=True),
        sa.Column("authorization__groups_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["authorization__groups_id"],
            ["authorization__groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["authorization__roles_id"],
            ["authorization__roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    _ = op.create_table(
        "authorization__users_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("users__users_id", sa.Uuid(), nullable=True),
        sa.Column("authorization__groups_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["authorization__groups_id"],
            ["authorization__groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["users__users_id"],
            ["users__users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("authorization__users_groups")
    op.drop_table("authorization__roles_groups")
    op.drop_table("authorization__groups")
    # ### end Alembic commands ###
